name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Adjust to your Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django
      - name: Collect static files
        run: python manage.py collectstatic --noinput
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          #azure_static_web_apps_api_token: #${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
          action: "upload"
          app_location: "/" # Root or "/workflow" if Django app is in subdirectory
          output_location: "staticfiles" # Adjust to your STATIC_ROOT
          skip_app_build: true # Skip Node.js build
          skip_api_build: true # Set to false if you have an API
  
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"

          